[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --baud 460800 --monitor --partition-table partitions.csv"

[build]
target = "riscv32imc-unknown-none-elf"
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",

  "-C", "link-arg=-Tlinkall.x",
]

[unstable]
build-std = ["core"]